import { Post } from '@/types/database';

export const INITIAL_POSTS: Post[] = [
  {
    id: '1',
    user_id: 'user-zxg',
    author: 'Zeyad Ashraf',
    author_avatar: '/assets/default-avatar.svg',
    text: 'Excited to unveil the complete Next.js 15 overhaul for Loppo! Built with the Linear craft design system (#010102 canvas, hairline borders, and lavender accents) wired to Supabase PostgreSQL with full Row-Level Security. Check it out and let me know your thoughts!',
    image_url: '/assets/og-image.png',
    video_url: null,
    category: 'Engineering',
    tags: ['Nextjs', 'Supabase', 'TailwindCSS', 'WebDev'],
    likes_count: 24,
    comments_count: 5,
    is_liked: false,
    is_saved: false,
    created_at: '2026-09-21T14:30:00Z',
    poll: {
      question: 'Which frontend architecture do you prefer for high-craft social web apps?',
      options: [
        { text: 'Next.js App Router + Server Actions', votes: 42 },
        { text: 'Native Web Components (Zero-Build)', votes: 18 },
        { text: 'Vite React SPA + REST API', votes: 12 },
      ],
      total_votes: 72,
    },
  },
  {
    id: '2',
    user_id: 'user-sophia',
    author: 'Sophia Chen',
    author_avatar: '/assets/default-avatar.svg',
    text: 'The subtle ambient radial glow in dark mode makes all the difference. When you switch accent colors, the entire page ambient light shifts naturally without breaking contrast ratios.',
    image_url: null,
    video_url: null,
    category: 'Design',
    tags: ['Linear', 'DesignSystems', 'UIUX'],
    likes_count: 18,
    comments_count: 3,
    is_liked: true,
    is_saved: true,
    created_at: '2026-09-21T15:10:00Z',
  },
  {
    id: '3',
    user_id: 'user-marcus',
    author: 'Marcus Vance',
    author_avatar: '/assets/default-avatar.svg',
    text: 'Benchmarking query times with Supabase RLS policies enabled. Reading from partitioned indexes gives sub-10ms latency across 50k mock comments. Absolutely loving Postgres full-text search as well.',
    image_url: null,
    video_url: null,
    category: 'Backend',
    tags: ['PostgreSQL', 'Performance', 'Database'],
    likes_count: 12,
    comments_count: 2,
    is_liked: false,
    is_saved: false,
    created_at: '2026-09-21T16:00:00Z',
  },
];
